<a href="https://colab.research.google.com/github/BibhuDas123/Deep_learning/blob/master/%5CNLP_with_Tensorflow%5CNLP_with_Tensorflow_with_TL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
from __future__ import absolute_import,division,print_function,unicode_literals
import tensorflow as tf
import os
import datetime
import tensorflow_datasets as tfds
import tensorflow_hub as hub
import numpy as np

In [41]:
datasets,info=tfds.load('amazon_us_reviews/Major_Appliances_v1_00',with_info=True,split=('train[:70%]','train[70%:85%]','train[85%:]'))

In [42]:
info

tfds.core.DatasetInfo(
    name='amazon_us_reviews',
    version=0.1.0,
    description='Amazon Customer Reviews (a.k.a. Product Reviews) is one of Amazons iconic products. In a period of over two decades since the first review in 1995, millions of Amazon customers have contributed over a hundred million reviews to express opinions and describe their experiences regarding products on the Amazon.com website. This makes Amazon Customer Reviews a rich source of information for academic researchers in the fields of Natural Language Processing (NLP), Information Retrieval (IR), and Machine Learning (ML), amongst others. Accordingly, we are releasing this data to further research in multiple disciplines related to understanding customer product experiences. Specifically, this dataset was constructed to represent a sample of customer evaluations and opinions, variation in the perception of a product across geographical regions, and promotional intent or bias in reviews.

Over 130+ million cus

In [43]:
train_dataset=datasets[0]
test_dataset=datasets[1]
val_dataset=datasets[2]

In [44]:
for reviews in train_dataset.take(2):
  print(reviews)

{'data': {'customer_id': <tf.Tensor: shape=(), dtype=string, numpy=b'48220985'>, 'helpful_votes': <tf.Tensor: shape=(), dtype=int32, numpy=0>, 'marketplace': <tf.Tensor: shape=(), dtype=string, numpy=b'US'>, 'product_category': <tf.Tensor: shape=(), dtype=string, numpy=b'Major Appliances'>, 'product_id': <tf.Tensor: shape=(), dtype=string, numpy=b'B002ZD5I16'>, 'product_parent': <tf.Tensor: shape=(), dtype=string, numpy=b'476878110'>, 'product_title': <tf.Tensor: shape=(), dtype=string, numpy=b'Whirlpool Part Number 4388736: DRUM'>, 'review_body': <tf.Tensor: shape=(), dtype=string, numpy=b'Just was described, works great, fast shipping!!'>, 'review_date': <tf.Tensor: shape=(), dtype=string, numpy=b'2015-04-08'>, 'review_headline': <tf.Tensor: shape=(), dtype=string, numpy=b'Perfect Fit'>, 'review_id': <tf.Tensor: shape=(), dtype=string, numpy=b'R2PIXJFK315V9F'>, 'star_rating': <tf.Tensor: shape=(), dtype=int32, numpy=5>, 'total_votes': <tf.Tensor: shape=(), dtype=int32, numpy=0>, 'ver

In [10]:
def target(x):
  if x>3:
    return 1
  else:
    return 0


In [45]:
for reviews in train_dataset.take(5):
  review_text=reviews['data']
  print(review_text.get('review_body').numpy())
  star_rating=review_text.get('star_rating')
  print(star_rating)
  print(target(star_rating))


b'Just was described, works great, fast shipping!!'
tf.Tensor(5, shape=(), dtype=int32)
1
b'Amazing replacement! I kept buying the exspensive name brand filters and decided to try this out. You could not tell the difference! Awesome product!'
tf.Tensor(5, shape=(), dtype=int32)
1
b"The round rubbers that holds the spin dryer usually break down into pieces that your spin dryer doesn't turned due to balance.. Good product keeping your clothes dry quickly, but bad because of the rubber shies break up.."
tf.Tensor(2, shape=(), dtype=int32)
0
b"Absolutely love my new laundry pod! The only thing that would make me love it more was if there was a left-handed option available. The green grip on the cover is awesome for my right-handed boyfriend; not so much for me. Granted, I could use it backwards, but it's so much cuter front facing!"
tf.Tensor(5, shape=(), dtype=int32)
1
b'We have had this refrigerator for 1 year.  The repairmen have come out 3 times and the ice maker/water dispenser still 

In [46]:
def fetch(tensor):
  text=tensor['data'].get('review_body')
  label=target(tensor['data'].get('star_rating'))
  return text,label

In [47]:
train_data_f=train_dataset.map(fetch)
test_data_f=test_dataset.map(fetch)
val_data_f=val_dataset.map(fetch)

In [48]:
train_data,train_labels=next(iter(train_data_f.batch(5)))
train_data

<tf.Tensor: shape=(5,), dtype=string, numpy=
array([b'Just was described, works great, fast shipping!!',
       b'Amazing replacement! I kept buying the exspensive name brand filters and decided to try this out. You could not tell the difference! Awesome product!',
       b"The round rubbers that holds the spin dryer usually break down into pieces that your spin dryer doesn't turned due to balance.. Good product keeping your clothes dry quickly, but bad because of the rubber shies break up..",
       b"Absolutely love my new laundry pod! The only thing that would make me love it more was if there was a left-handed option available. The green grip on the cover is awesome for my right-handed boyfriend; not so much for me. Granted, I could use it backwards, but it's so much cuter front facing!",
       b'We have had this refrigerator for 1 year.  The repairmen have come out 3 times and the ice maker/water dispenser still is not right.  Water freezes up in the top of the refrigerator; ice 

In [49]:
train_labels

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 1, 0, 1, 0], dtype=int32)>

In [50]:
embedding='https://tfhub.dev/google/tf2-preview/nnlm-en-dim128-with-normalization/1'
hub_layer=hub.KerasLayer(embedding,input_shape=[],dtype=tf.string,trainable=True)
hub_layer(train_data[:1])

<tf.Tensor: shape=(1, 128), dtype=float32, numpy=
array([[ 0.22712293, -0.04044884,  0.01981788,  0.12293088, -0.01956631,
        -0.07215592,  0.0999354 , -0.02269012,  0.06228581,  0.03487423,
         0.08390489,  0.01938753, -0.06078235, -0.08141041, -0.08112923,
         0.12206675, -0.05444637,  0.01776398,  0.06085176,  0.00782775,
         0.13016488, -0.08578901,  0.07075448,  0.09239391,  0.03195481,
        -0.18742383,  0.08335388, -0.07610522,  0.13958925,  0.08128966,
        -0.06690247,  0.02422436, -0.08120105,  0.16699426,  0.07105717,
         0.04976164,  0.06158045, -0.05609883,  0.03094825,  0.1630568 ,
         0.06370129, -0.07717431, -0.01477074, -0.01505845,  0.05466522,
         0.06274084,  0.0147941 , -0.1173359 ,  0.08766245,  0.10317444,
         0.12939715, -0.06983662, -0.05874728,  0.01237082,  0.00365009,
        -0.00051225,  0.07233465, -0.10375941,  0.02632711, -0.2072623 ,
         0.09365123,  0.00211447,  0.07495772, -0.11837892,  0.01267919,
 

In [51]:
model = tf.keras.Sequential()
model.add(hub_layer)
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dropout(0.25))
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

In [52]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
keras_layer_1 (KerasLayer)   (None, 128)               124642688 
_________________________________________________________________
dense_2 (Dense)              (None, 16)                2064      
_________________________________________________________________
dropout_1 (Dropout)          (None, 16)                0         
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 17        
Total params: 124,644,769
Trainable params: 124,644,769
Non-trainable params: 0
_________________________________________________________________


In [53]:
model.compile(optimizer='adam',loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),metrics=['accuracy'])


In [54]:
train_data_f=train_data_f.shuffle(7000).batch(512)
val_data_f=val_data_f.batch(512)

In [55]:
history=model.fit(train_data_f,epochs=2,validation_data=val_data_f,verbose=1)
result=model.evaluate(test_data_f.batch(512),verbose=2)

Epoch 1/2
133/133 [==============================] - 174s 1s/step - loss: 0.5572 - accuracy: 0.7837 - val_loss: 0.5039 - val_accuracy: 0.8800
Epoch 2/2
133/133 [==============================] - 168s 1s/step - loss: 0.4949 - accuracy: 0.8943 - val_loss: 0.4929 - val_accuracy: 0.8918
29/29 - 5s - loss: 0.4943 - accuracy: 0.8922


In [ ]:
print(results)

In [57]:
for f0,f1 in test_data_f.batch(1500):
  y=f1
  y_pred=tf.where(model.predict(f0)>0.5,1,0)
  print(tf.math.confusion_matrix(labels=y,predictions=y_pred,num_classes=2))

tf.Tensor(
[[426  64]
 [ 91 919]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[391  72]
 [ 80 957]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[440  89]
 [ 84 887]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[434  65]
 [ 76 925]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[431  73]
 [ 91 905]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[421  87]
 [ 85 907]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[396  71]
 [ 93 940]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[407  80]
 [ 84 929]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[451  66]
 [ 97 886]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[318  56]
 [ 63 598]], shape=(2, 2), dtype=int32)
